# Generated by Django 4.0.2 on 2022-03-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='orderId',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='paymentId',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='paymentsignature',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
