# Generated by Django 4.0.2 on 2022-03-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_alter_contact_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
